version: '3.8'
volumes:
  db:
    driver:
      local
x-common-variables: &common-db-variables
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: fam
   POSTGRES_PORT: 5432
   POSTGRES_HOST_AUTH_METHOD: trust
   api_db_username: fam_proxy_api
   api_db_password: test
services:
  # todo: add migration for database
  db:
    container_name: db
    image: postgres:14.1-alpine
    #env_file:
    #  - env-db-dev.env
    environment: *common-db-variables
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fam
  fam-api:
    container_name: fam-api
    depends_on:
      - db
    #env_file:
    #  - env-db-dev.env
    environment:
      <<: *common-db-variables
      POSTGRES_DB: fam
      POSTGRES_HOST: db
    entrypoint:
      - bash
      - -c
      -  cd /usr/src && echo DB USER is $api_db_username &&
        pip install -r requirements.txt  -r requirements-dev.txt &&
        cd api &&
        alembic -x url=postgresql+psycopg2://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@$${POSTGRES_HOST}:$${POSTGRES_PORT}/$${POSTGRES_DB} upgrade head &&
        cd .. &&
        uvicorn api.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    image: python:3.8
    networks:
      - fam

networks:
  fam:
    driver: bridge
    attachable: true

      #     #driver: bridge
#     name: pre-existing
#     attachable: true
#     external: true