version: '3.8'
volumes:
  db:
    driver:
      local
services:
  # todo: add migration for database
  db:
    container_name: db
    image: postgres:14.1-alpine
    env_file:
      - env-db-dev.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fam
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fam
  fam-api:
    container_name: fam-api
    #build: ./
    env_file:
      - env-db-dev.env
    entrypoint:
      - sh
      - -c
      -  cd /usr/src &&
        ls -la &&
        python3 -m venv venvdc &&
        . ./venvdc/bin/activate &&
        pip install -r requirements.txt  -r requirements-dev.txt &&
        uvicorn api.app.main:app --reload --workers 1 --host localhost --port 8000
    #command: uvicorn api.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    image: python:3.8
    networks:
      - fam

networks:
  fam:
    driver: bridge
    attachable: true
    # ingress: true

      #     #driver: bridge
#     name: pre-existing
#     attachable: true
#     external: true