/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthCallbackHandler: typeof import('./src/components/AuthCallbackHandler.vue')['default']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    ForestClientCard: typeof import('./src/components/common/ForestClientCard.vue')['default']
    GrantAccess: typeof import('./src/components/GrantAccess.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ManageAccess: typeof import('./src/components/ManageAccess.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RadioGroup: typeof import('./src/components/common/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectApplication: typeof import('./src/components/SelectApplication.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
  }
}
