# Note, the compose service name and container_name for "fam-database" and "fam-flyway" are named differently
# than the main application docker-compose so that when testcontainer is up it does not delete previous running main container.
---

services:
  fam-database-testcontainer:
    extends:
      file: docker-base-services.yml
      service: fam-database
    container_name: fam-postgres-testcontainer
    ports:
      - "${POSTGRES_PORT_TESTCONTAINER}:${POSTGRES_PORT}"  # use host-port: '5433' for testcontainer db instance than '5432' for main db.

  fam-flyway-testcontainer:
    extends:
      file: docker-base-services.yml
      service: fam-flyway
    environment:
      # note: this environment is separated out for testcontainer to avoid colliding with main app db instance.
      # And in the docker network it is still prot '5432'
      - FLYWAY_URL=jdbc:postgresql://fam-postgres-testcontainer:${POSTGRES_PORT}/fam
    depends_on:
      fam-database-testcontainer:
        condition: service_healthy

  fam-test-nginx:
    image: nginx:latest
    container_name: fam-test-nginx
    ports:
      - "8181:80"
    depends_on:
      fam-flyway-testcontainer:
        condition: service_completed_successfully

networks:
  fam:
    driver: bridge