---
version: "3.8"
services:
  fam-database:
    image: postgres:14.1-alpine
    container_name: fam-postgres
    mem_limit: 128m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fam
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5342
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - fam

  fam-flyway:
    image: flyway/flyway:latest-alpine
    container_name: fam-api-migrations
    command:
      - info
      - migrate
      - info
    volumes:
      - "./server/flyway/sql:/flyway/sql"
    environment:
      - FLYWAY_URL=jdbc:postgresql://fam-database:5432/fam
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=test
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_PLACEHOLDERS_api_db_username=fam_proxy_api
      - FLYWAY_PLACEHOLDERS_api_db_password=test
    depends_on:
      - fam-database
    networks:
      - fam
networks:
  fam:
    driver: bridge