---
version: "3.8"
services:
  fam-database:
    extends:
      file: docker-base-services.yml
      service: fam-database

  fam-flyway:
    extends:
      file: docker-base-services.yml
      service: fam-flyway
    depends_on:
      fam-database:
        condition: service_healthy

networks:
  fam:
    driver: bridge