# Note, This is the services definition not the actual compose file for running services.
#       The original docker-compose file uses 'extends' feature to include this with limitation.
# Ref: https://docs.docker.com/compose/extends/#multiple-compose-files
#      From its note "Keep in mind that `volumes_from`` and `depends_on`` are never shared between services using extends.
#      These exceptions exist to avoid implicit dependencies; you always define volumes_from locally."
#
---
services:
    fam-database:
        image: postgres:16.6-alpine
        mem_limit: 128m
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fam
            - POSTGRES_HOST_AUTH_METHOD=password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 6
        networks:
            - fam

    fam-flyway:
        build:
            context: server/flyway
            dockerfile: Dockerfile
        environment:
            - FLYWAY_USER=postgres
            - FLYWAY_PASSWORD=postgres
            - FLYWAY_BASELINE_ON_MIGRATE=true
            - FLYWAY_PLACEHOLDERS_api_db_username=fam_proxy_api
            - FLYWAY_PLACEHOLDERS_api_db_password=test
            - FLYWAY_PLACEHOLDERS_admin_management_api_db_user=fam_admin_management_api
            - FLYWAY_PLACEHOLDERS_admin_management_api_db_password=test
            - FLYWAY_PLACEHOLDERS_client_id_fom_public="nolongerinuse1"
            - FLYWAY_PLACEHOLDERS_client_id_fom_ministry="nolongerinuse2"
            - FLYWAY_PLACEHOLDERS_client_id_fam_console=26tltjjfe7ktm4bte7av998d78
            - FLYWAY_PLACEHOLDERS_client_id_dev_fom_oidc_client=1a8pkq0psq0daj5e6ir3ppcjkj
            - FLYWAY_PLACEHOLDERS_client_id_test_fom_oidc_client=7b6eki43nahus9ca0lhjs6m568
            - FLYWAY_PLACEHOLDERS_client_id_prod_fom_oidc_client=1rhdfiek5ntmk2kg39d6e31p46
            - FLYWAY_PLACEHOLDERS_client_id_dev_spar_oidc_client=xxqiHFmwG8j1cVAz7NgtknaZOt
            - FLYWAY_PLACEHOLDERS_client_id_test_spar_oidc_client=dm5Xkmomnq0gbwBiXiN5LgAna2
            - FLYWAY_PLACEHOLDERS_client_id_prod_spar_oidc_client=KdnD2eGS3Zcx494p04yMFhDwSf
            - FLYWAY_PLACEHOLDERS_client_id_dev_forest_client_oidc_client=xxqiHFmwG8j1cVAz7NgtknaZOg
            - FLYWAY_PLACEHOLDERS_client_id_test_forest_client_oidc_client=dm5Xkmomnq0gbwBiXiN5LgAnah
            - FLYWAY_PLACEHOLDERS_client_id_prod_forest_client_oidc_client=KdnD2eGS3Zcx494p04yMFhDwSe
            - FLYWAY_PLACEHOLDERS_client_id_dev_silva_oidc_client=xxqiHFmwG8j1cVAz7NgtknaZO5
            - FLYWAY_PLACEHOLDERS_client_id_test_silva_oidc_client=dm5Xkmomnq0gbwBiXiN5LgAna5
            - FLYWAY_PLACEHOLDERS_client_id_prod_silva_oidc_client=KdnD2eGS3Zcx494p04yMFhDwS5
            - FLYWAY_PLACEHOLDERS_auth_lambda_db_user=fam_auth_lambda
            - FLYWAY_PLACEHOLDERS_auth_lambda_db_password=test
            - FLYWAY_PLACEHOLDERS_client_id_dev_apt_oidc_client=Tz6oJkY3d1qVZmFLEr8BucxGf9
            - FLYWAY_PLACEHOLDERS_client_id_test_apt_oidc_client=bV4Nm7CdQXy1a2UTzg9JhEPksw
            - FLYWAY_PLACEHOLDERS_client_id_prod_apt_oidc_client=gR0qA8vXKMj5bnc6tT2YDL3rWz
            - FLYWAY_PLACEHOLDERS_client_id_dev_results_exam_oidc_client=Kp9tLwXfZ2eVq7MJyR3HcAbDn4
            - FLYWAY_PLACEHOLDERS_client_id_test_results_exam_oidc_client=Zw3NhEYkLmX1r0Vq8Tp5BsUad7
            - FLYWAY_PLACEHOLDERS_client_id_prod_results_exam_oidc_client=Xa7BvQJdT9mz6PgCyW4LtKHue2
            - FLYWAY_PLACEHOLDERS_client_id_dev_ilcr_oidc_client=1c6rh45nhrdtlialfinrdar4e2
            - FLYWAY_PLACEHOLDERS_client_id_test_ilcr_oidc_client=3th04vu15tasm5ouf49q6afbur
            - FLYWAY_PLACEHOLDERS_client_id_prod_ilcr_oidc_client=6q2nco5v8rg3enjm5khfig9f7n
        networks:
            - fam
