---
version: "3.8"
services:
  fam-database:
    image: postgres:14.1-alpine
    container_name: fam-postgres
    mem_limit: 128m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fam
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - fam

  fam-flyway:
    image: flyway/flyway:latest-alpine
    container_name: fam-api-migrations
    command:
      - info
      - migrate
      - info
    volumes:
      - "./server/flyway/sql:/flyway/sql"
    environment:
      - FLYWAY_URL=jdbc:postgresql://fam-postgres:5432/fam
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=test
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_PLACEHOLDERS_api_db_username=fam_proxy_api
      - FLYWAY_PLACEHOLDERS_api_db_password=test
      - FLYWAY_PLACEHOLDERS_client_id_fam_console=26tltjjfe7ktm4bte7av998d78
      - FLYWAY_PLACEHOLDERS_client_id_fom_public=2c7lo6rqp983km60u3p3heqeds
      - FLYWAY_PLACEHOLDERS_client_id_fom_ministry=gsbm3p62isc2ju807f0imu29s
    depends_on:
      fam-database:
        condition: service_healthy
    networks:
      - fam

  fam-api:
    container_name: fam-api
    environment:
      - POSTGRES_DB=fam
      - POSTGRES_HOST=fam-database
      - api_db_username=fam_proxy_api
      - api_db_password=test
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - fam-flyway
    ports:
      - 8000:8000
    networks:
      - fam

networks:
  fam:
    driver: bridge