---
version: "3.8"
services:
  fam-database:
    extends:
      file: docker-base-services.yml
      service: fam-database

  fam-flyway:
    extends:
      file: docker-base-services.yml
      service: fam-flyway
    depends_on:
      fam-database:
        condition: service_healthy

  fam-api:
    container_name: fam-api
    environment:
      - POSTGRES_HOST=fam-postgres # overrides 'localhost' in local-dev.env
    env_file: server/backend/local-dev.env
    build:
      context: server/backend
      dockerfile: Dockerfile
    depends_on:
      - fam-flyway
    ports:
      - 8000:8000
    networks:
      - fam

networks:
  fam:
    driver: bridge