# Note, This is the services definition not the actual compose file for running services.
#       The original docker-compose file uses 'extends' feature to include this with limitation.
# Ref: https://docs.docker.com/compose/extends/#multiple-compose-files
#      From its note "Keep in mind that `volumes_from`` and `depends_on`` are never shared between services using extends.
#      These exceptions exist to avoid implicit dependencies; you always define volumes_from locally."
#
---
services:
    fam-database:
        image: postgres:16.6-alpine
        mem_limit: 128m
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fam
            - POSTGRES_HOST_AUTH_METHOD=password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 6
        networks:
            - fam

    fam-flyway:
        build:
            context: server/flyway
            dockerfile: Dockerfile
        environment:
            - FLYWAY_USER=postgres
            - FLYWAY_PASSWORD=postgres
            - FLYWAY_BASELINE_ON_MIGRATE=true
            - FLYWAY_PLACEHOLDERS_api_db_username=fam_proxy_api
            - FLYWAY_PLACEHOLDERS_api_db_password=test
            - FLYWAY_PLACEHOLDERS_admin_management_api_db_user=fam_admin_management_api
            - FLYWAY_PLACEHOLDERS_admin_management_api_db_password=test
            - FLYWAY_PLACEHOLDERS_client_id_fom_public="nolongerinuse1"
            - FLYWAY_PLACEHOLDERS_client_id_fom_ministry="nolongerinuse2"
            - FLYWAY_PLACEHOLDERS_client_id_fam_console=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_fom_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_fom_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_fom_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_spar_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_spar_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_spar_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_forest_client_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_forest_client_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_forest_client_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_silva_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_silva_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_silva_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_auth_lambda_db_user=fam_auth_lambda
            - FLYWAY_PLACEHOLDERS_auth_lambda_db_password=test
            - FLYWAY_PLACEHOLDERS_client_id_dev_apt_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_apt_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_apt_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_results_exam_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_results_exam_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_results_exam_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_ilcr_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_test_ilcr_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_prod_ilcr_oidc_client=flywayplaceholder
            - FLYWAY_PLACEHOLDERS_client_id_dev_waste_plus_oidc_client="flywayplaceholder"
            - FLYWAY_PLACEHOLDERS_client_id_test_waste_plus_oidc_client="flywayplaceholder"
            - FLYWAY_PLACEHOLDERS_client_id_prod_waste_plus_oidc_client="flywayplaceholder"
            - FLYWAY_PLACEHOLDERS_client_id_dev_apt3_oidc_client="flywayplaceholder"
            - FLYWAY_PLACEHOLDERS_client_id_test_apt3_oidc_client="flywayplaceholder"
            - FLYWAY_PLACEHOLDERS_client_id_prod_apt3_oidc_client="flywayplaceholder"
        networks:
            - fam
