---
services:
  fam-database:
    extends:
      file: docker-base-services.yml
      service: fam-database
    container_name: fam-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  fam-flyway:
    extends:
      file: docker-base-services.yml
      service: fam-flyway
    environment:
      - FLYWAY_URL=jdbc:postgresql://fam-postgres:${POSTGRES_PORT}/fam
    depends_on:
      fam-database:
        condition: service_healthy

  fam-api:
    container_name: fam-api
    env_file: server/backend/local-dev.env
    environment:
      - POSTGRES_HOST=fam-postgres # overrides 'localhost' in local-dev.env
    build:
      context: server/backend
      dockerfile: Dockerfile
    depends_on:
      - fam-flyway
    ports:
      - 8000:8000
    networks:
      - fam

  fam-admin-management-api:
    container_name: fam-admin-management-api
    env_file: server/admin_management/local-dev.env
    environment:
      - POSTGRES_HOST=fam-postgres # overrides 'localhost' in local-dev.env
    build:
      context: server/admin_management
      dockerfile: Dockerfile
    depends_on:
      - fam-flyway
    ports:
      - 8001:8001
    networks:
      - fam

networks:
  fam:
    driver: bridge
