"""fixing definitions for fam_application_client and fam_user

Revision ID: V11
Revises: V10
Create Date: 2022-10-19 14:53:52.504085

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V11'
down_revision = 'V10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fam_application_client', 'update_date',
               existing_type=sa.VARCHAR(length=9),
               nullable=False,
               comment='The date and time the record was created.',
               existing_comment='ZIP code.',
               existing_server_default=sa.text('LOCALTIMESTAMP'),
               schema='app_fam')

    op.alter_column('fam_user', 'cognito_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text(u"''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fam_application_client', 'update_date',
               existing_type=sa.VARCHAR(length=9),
               nullable=True,
               comment='ZIP code.',
               existing_comment='The date and time the record was created.',
               existing_server_default=sa.text('LOCALTIMESTAMP'),
               schema='app_fam')

    op.alter_column('fam_user', 'cognito_user_id',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=32),
            existing_nullable=True,
            existing_server_default=sa.text(u"''::character varying"))

    # ### end Alembic commands ###
