"""misc changes to support auth

Revision ID: V11
Revises: V10
Create Date: 2022-10-20 15:11:50.669658

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'V11'
down_revision = 'V10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fam_application_client', 'update_date',
               existing_type=sa.VARCHAR(length=9),
               type_=postgresql.TIMESTAMP(precision=6),
               nullable=False,
               comment='The date and time the record was created.',
               existing_comment='ZIP code.',
               existing_server_default=sa.text('LOCALTIMESTAMP'),
               schema='app_fam',
               postgresql_using='update_date::timestamp(6) without time zone')
    op.create_unique_constraint('cognito_app_uk', 'fam_application_client', ['cognito_client_id', 'application_id'], schema='app_fam')
    op.alter_column('fam_user', 'cognito_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='app_fam')
    # ### end Alembic commands ###
    # ALTER TABLE app_fam.fam_application_client alter COLUMN update_date type timestamp(6) USING update_date::timestamp(6) without time zone;


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fam_user', 'cognito_user_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True,
               schema='app_fam')
    op.drop_constraint('cognito_app_uk', 'fam_application_client', schema='app_fam', type_='unique')
    op.alter_column('fam_application_client', 'update_date',
               existing_type=postgresql.TIMESTAMP(precision=6),
               type_=sa.VARCHAR(length=9),
               nullable=True,
               comment='ZIP code.',
               existing_comment='The date and time the record was created.',
               existing_server_default=sa.text('LOCALTIMESTAMP'),
               schema='app_fam')
    # ### end Alembic commands ###
