"""add_roles

Revision ID: V12
Revises: V11
Create Date: 2022-12-02 12:04:17.220467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V12'
down_revision = 'V11'
branch_labels = None
depends_on = None

migrate_sql_str = """
INSERT INTO app_fam.fam_role (
    role_name,
    role_purpose,
    application_id,
    role_type_code,
    create_user
)
VALUES (
    'FAM_ACCESS_ADMIN',
    'Provides the privilege to assign or unassign all roles for FAM',
    (select application_id from app_fam.fam_application where application_name = 'fam'),
    'C',
    CURRENT_USER
)
;

INSERT INTO app_fam.fam_role (
    role_name,
    role_purpose,
    application_id,
    role_type_code,
    create_user
)
VALUES (
    'FOM_ACCESS_ADMIN',
    'Provides the privilege to assign or unassign all roles for FOM',
    (select application_id from app_fam.fam_application where application_name = 'fam'),
    'C',
    CURRENT_USER
)
;

INSERT INTO app_fam.fam_role (
    role_name,
    role_purpose,
    application_id,
    role_type_code,
    create_user
)
VALUES (
    'FOM_SUBMITTER',
    'Provides the privilege to submit a FOM (on behalf of a specific forest client)',
    (select application_id from app_fam.fam_application where application_name = 'fom'),
    'A',
    CURRENT_USER
)
;

INSERT INTO app_fam.fam_role (
    role_name,
    role_purpose,
    application_id,
    role_type_code,
    create_user
)
VALUES (
    'FOM_REVIEWER',
    'Provides the privilege to review all FOMs in the system',
    (select application_id from app_fam.fam_application where application_name = 'fom'),
    'C',
    CURRENT_USER
)
;
"""



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    statements = migrate_sql_str.replace('\n', '').split(';')
    for statement in statements:
        # make sure its not just a blank line
        if statement:
            op.execute(statement)
            print(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
