"""add_roles_app_clients

Revision ID: V13
Revises: V12
Create Date: 2022-12-02 12:15:44.678454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V13'
down_revision = 'V12'
branch_labels = None
depends_on = None


client_id_fam_console = '26tltjjfe7ktm4bte7av998d78'
client_id_fom_public = '2c7lo6rqp983km60u3p3heqeds'
client_id_fom_ministry = 'gsbm3p62isc2ju807f0imu29s'

migrate_sql_str = f"""
INSERT INTO app_fam.fam_application_client (
    cognito_client_id,
    application_id,
    create_user
)
VALUES (
    '{client_id_fam_console}',
    (select application_id from app_fam.fam_application where application_name = 'fam'),
    CURRENT_USER
)
;

INSERT INTO app_fam.fam_application_client (
    cognito_client_id,
    application_id,
    create_user
)
VALUES (
    '{client_id_fom_public}',
    (select application_id from app_fam.fam_application where application_name = 'fom'),
    CURRENT_USER
)
;

INSERT INTO app_fam.fam_application_client (
    cognito_client_id,
    application_id,
    create_user
)
VALUES (
    '{client_id_fom_ministry}',
    (select application_id from app_fam.fam_application where application_name = 'fom'),
    CURRENT_USER
)
;


"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # None autogenerated
    # ### end Alembic commands ###
    statements = migrate_sql_str.replace('\n', '').split(';')
    for statement in statements:
        # make sure its not just a blank line
        if statement:
            op.execute(statement)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
