"""revise user code descr

Revision ID: V14
Revises: V13
Create Date: 2022-12-02 14:17:07.010276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V14'
down_revision = 'V13'
branch_labels = None
depends_on = None


migrate_sql_str = """
UPDATE app_fam.fam_user_type_code SET description = 'BCEID' WHERE user_type_code = 'B';
UPDATE app_fam.fam_user_type_code SET description = 'IDIR' WHERE user_type_code = 'I';
"""

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    statements = migrate_sql_str.replace('\n', '').split(';')
    for statement in statements:
        # make sure its not just a blank line
        if statement:
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
