"""fix db permissions

Revision ID: V15
Revises: V14
Create Date: 2022-12-12 13:47:33.360585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import os
import logging

LOGGER = logging.getLogger(__name__)


# revision identifiers, used by Alembic.
revision = 'V15'
down_revision = 'V14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    fam_proxy_api = os.getenv('api_db_username')
    grant_sql = f"""GRANT SELECT, UPDATE, DELETE, INSERT
                ON ALL TABLES IN SCHEMA app_fam TO
                {fam_proxy_api}"""
    op.get_bind()
    LOGGER.debug(f'exec: {grant_sql}')
    op.execute(grant_sql)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
