"""remove forest client client_name column

Revision ID: V16
Revises: V15
Create Date: 2022-12-08 14:37:19.065133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V16'
down_revision = 'V15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fam_for_cli_name_uk', 'fam_forest_client', schema='app_fam', type_='unique')
    op.drop_index('ix_app_fam_fam_forest_client_client_name', table_name='fam_forest_client', schema='app_fam')
    op.drop_column('fam_forest_client', 'client_name', schema='app_fam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fam_forest_client', sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='app_fam')
    op.create_index('ix_app_fam_fam_forest_client_client_name', 'fam_forest_client', ['client_name'], unique=False, schema='app_fam')
    op.create_unique_constraint('fam_for_cli_name_uk', 'fam_forest_client', ['client_name'], schema='app_fam')
    # ### end Alembic commands ###
