"""first application

Revision ID: V2
Revises: V1
Create Date: 2022-09-01 09:46:38.798508

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models.model



# revision identifiers, used by Alembic.
revision = 'V2'
down_revision = 'V1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    famApp = app.models.model.FamApplication.__table__
    op.bulk_insert(famApp,
        [
            {'application_name': 'fam',
            'application_description': 'Forests Access Management',
            'create_user': 'fam_proxy_api',
            'update_user': 'fam_proxy_api'
            },
            {'application_name': 'fom',
            'application_description': 'Forest Operations Map',
            'create_user': 'fam_proxy_api',
            'update_user': 'fam_proxy_api'
            }
        ]
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
