"""adding role type

Revision ID: V6
Revises: V5
Create Date: 2022-09-21 12:10:41.567875

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V6'
down_revision = 'V5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fam_role', sa.Column('role_type', sa.String(length=15), nullable=False, comment='Identifies if the role is a parent or child role.  Users should only be assigned to roles where role_type=child'), schema='app_fam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fam_role', 'role_type', schema='app_fam')
    # ### end Alembic commands ###
