"""add forest_client_number column to store id as string

Revision ID: V7
Revises: V6
Create Date: 2022-09-30 22:01:41.878742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'V7'
down_revision = 'V6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fam_forest_client', sa.Column('forest_client_number', sa.String(), nullable=False, comment='Id number as String from external Forest Client source(api/table) that identifies the Forest Client.'), schema='app_fam')
    op.create_unique_constraint('fam_for_cli_num_uk', 'fam_forest_client', ['forest_client_number'], schema='app_fam')
    op.create_index(op.f('ix_app_fam_fam_forest_client_client_name'), 'fam_forest_client', ['client_name'], unique=False, schema='app_fam')
    op.create_index(op.f('ix_app_fam_fam_forest_client_forest_client_number'), 'fam_forest_client', ['forest_client_number'], unique=False, schema='app_fam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_fam_fam_forest_client_forest_client_number'), table_name='fam_forest_client', schema='app_fam')
    op.drop_index(op.f('ix_app_fam_fam_forest_client_client_name'), table_name='fam_forest_client', schema='app_fam')
    op.drop_constraint('fam_for_cli_num_uk', 'fam_forest_client', schema='app_fam', type_='unique')
    op.drop_column('fam_forest_client', 'forest_client_number', schema='app_fam')
    # ### end Alembic commands ###
