BEGIN;

-- Running upgrade V10 -> V11

ALTER TABLE app_fam.fam_forest_client ALTER COLUMN client_number_id SET NOT NULL;

ALTER TABLE app_fam.fam_forest_client ALTER COLUMN client_number_id SET GENERATED BY DEFAULT;

COMMENT ON COLUMN app_fam.fam_forest_client.client_number_id IS 'Sequentially assigned number to identify a ministry client.';

UPDATE alembic_version SET version_num='V11' WHERE alembic_version.version_num = 'V10';

COMMIT;

