-- Create fam_application_admin table
CREATE TABLE IF NOT EXISTS app_fam.fam_application_admin
(
    application_admin_id        bigint          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id                     bigint          NOT NULL,
    application_id              bigint          NOT NULL,
    create_user                 varchar(30)     NOT NULL,
    create_date                 timestamp(6)    DEFAULT CURRENT_DATE NOT NULL,
    update_user                 varchar(30),
    update_date                 timestamp(6)    DEFAULT CURRENT_DATE
);

-- Add table/column comments
COMMENT ON TABLE app_fam.fam_application_admin IS 'Application Admin is a cross-reference object that allows for the identification of who are the administrators(User) for an Application, as well as which Applications the User can administer.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.application_admin_id IS 'Automatically generated key used to identify the uniqueness of a User administers the Application.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.user_id IS 'Unique ID to reference and identify the user within FAM system.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.application_id IS 'Unique ID to reference and identify the application within FAM system.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.create_user IS 'The user or proxy account that created the record.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.create_date IS 'The date and time the record was created.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.update_user IS 'The user or proxy account that created or last updated the record.'
;
COMMENT ON COLUMN app_fam.fam_application_admin.update_date IS 'The date and time the record was created or last updated.'
;

-- Create index
CREATE INDEX ix_app_fam_fam_application_admin_user_id ON app_fam.fam_application_admin (user_id)
;
CREATE INDEX ix_app_fam_fam_application_admin_application_id ON app_fam.fam_application_admin (application_id)
;

-- Add constraints
ALTER TABLE app_fam.fam_application_admin ADD CONSTRAINT fam_app_admin_pk PRIMARY KEY (application_admin_id)
;
ALTER TABLE app_fam.fam_application_admin ADD CONSTRAINT Reffam_application_admin_application
    FOREIGN KEY (application_id)
    REFERENCES app_fam.fam_application(application_id)
;
ALTER TABLE app_fam.fam_application_admin ADD CONSTRAINT Reffam_application_admin_user
    FOREIGN KEY (user_id)
    REFERENCES app_fam.fam_user(user_id)
;

-- Add proxy user and grant privileges
CREATE USER ${admin_mgmt_api_db_user} WITH NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${admin_mgmt_api_db_password}'
;
GRANT USAGE ON SCHEMA app_fam TO ${admin_mgmt_api_db_user}
;
-- -- on 'fam_application_admin' table
GRANT SELECT, UPDATE, DELETE, INSERT ON app_fam.fam_application_admin TO ${admin_mgmt_api_db_user}
;
-- -- on 'fam_application' and 'fam_user' tables for new api proxy user.
GRANT SELECT, UPDATE, DELETE, INSERT ON app_fam.fam_application TO ${admin_mgmt_api_db_user}
;
GRANT SELECT, UPDATE, DELETE, INSERT ON app_fam.fam_user TO ${admin_mgmt_api_db_user}
;

