BEGIN;

-- Running upgrade V2 -> V3

CREATE TABLE IF NOT EXISTS alembic_version
(
    version_num character varying(32),
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

ALTER TABLE app_fam.fam_role ALTER COLUMN application_id DROP NOT NULL;

ALTER TABLE app_fam.fam_role ALTER COLUMN client_number_id DROP NOT NULL;

-- previous migrations originated from flyway / er studio code
-- beyond version 3 <this version> the migration code will be autogenerated
-- At this stage the AWS version of the db will have just created the
-- alembic version table so the update call becomes an insert
-- UPDATE alembic_version SET version_num='V3' WHERE alembic_version.version_num = 'V2';
INSERT into alembic_version (version_num) values ('V3');
COMMIT;

