export const TEST_FOREST_CLIENT_NAME = 'TEST';

export const TEST_SUCCESS_FOREST_CLIENT_NUMBER = '00000001';
export const TEST_SUCCESS_FOREST_CLIENT_NUMBER_2 = '00000004';
export const TEST_SUCCESS_FOREST_CLIENT_NUMBER_3 = '00001011';
export const TEST_INACTIVE_FOREST_CLIENT_NUMBER = '00000002';
export const TEST_INACTIVE_FOREST_CLIENT_NUMBER_2 = '00000003';
export const TEST_INACTIVE_FOREST_CLIENT_NUMBER_3 = '00000005';
export const TEST_INVALID_FOREST_CLIENT_NUMBER = '00000042';

export const STATUS_CODE_INACTIVE = 'I';
export const STATUS_CODE_ACTIVE = 'A';

export const STATUS_DESCRIPTION_INACTIVE = 'Inactive';
export const STATUS_DESCRIPTION_ACTIVE = 'Active';
