openapi: 3.0.1
info:
  title: Startup Sample Project
  description: Spec for BC Gov Startup Sample Project Screening API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://startup-sample-project.gov.bc.ca/api/v1
paths:
  /form:
    post:
      summary: Submit a new form greeting selection
      requestBody:
        description: Form data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        400:
          description: Invalid input
components:
  schemas:
    Form:
      required:
      - greeting
      type: object
      properties:
        greeting:
          type: string
    Response:
      type: object
      properties:
        id:
          type: string
        isolationPlanStatus:
          type: boolean
