declare module '@carbon/icons-vue/es/checkmark--filled/20'
declare module '@carbon/icons-vue/es/close/16';
declare module '@carbon/icons-vue/es/user--follow/16';
declare module '@carbon/icons-vue/es/help/16'
declare module '@carbon/icons-vue/es/error--filled/32';
declare module '@carbon/icons-vue/es/add/20';
declare module '@carbon/icons-vue/es/search/16';
declare module '@carbon/icons-vue/es/user--avatar--filled/20';
declare module '@carbon/icons-vue/es/user--avatar/20';
declare module '@carbon/icons-vue/es/login/20';