name: Test Auth Lambda

on:
  push:
    branches: [feat/23-authorization-lambda]

env:
  environment: dev
  organization: bcgov

jobs:
  test-auth-lambda:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: checkout the nr-forests-access-management repository
        uses: actions/checkout@v2
        # with: 
        #   path: "nr-forests-access-management"  

      - name: run flyway on test database
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/db
          user: user
          password: password
          locations: server/flyway/sql
        env: 
          FLYWAY_PLACEHOLDERS_API_DB_USERNAME: appuser
          FLYWAY_PLACEHOLDERS_API_DB_PASSWORD: appuserpw

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Auth function install python test dependencies
        run: |
          pip install pytest pytest-md pytest-emoji
          cd server/auth_function
          pip install -r requirements.txt

      - name: Auth function run pytest
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
        env: 
          PG_HOST: postgres
          PG_PORT: 5432
          PG_DATABASE: db
          PG_USER: appuser
          PG_PASSWORD: appuserpw

      - name: Auth function zip
        run: |
          mkdir packaging
          cd packaging
          pip install -t . -r ../requirements.txt
          zip -r9 ../../fam_auth_function.zip .
          cd ..
          rm -rf packaging
          cd ..
          zip -u ../fam_auth_function.zip -r auth_function/
          cd ..          

      - name: Auth function upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: fam-auth-function
          path: ./server/fam_auth_function.zip
          if-no-files-found: error