name: Continuous Integration Backend
on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "server/**"


jobs:
  auth_function_ci:
    uses: ./.github/workflows/reusable_auth_function_ci.yml
