name: Continuous Integration Backend
on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - "server/**"


jobs:
  auth_function_ci:
    uses: ./.github/workflows/reusable_auth_function_ci.yml
    secrets: inherit

  api_tests:
    uses: ./.github/workflows/reuseable_api_unittests.yml
    secrets: inherit
