name: Continuous Integration Backend
on:
  pull_request:
    branches:
      - "main"

jobs:
  auth_function_ci:
    uses: ./.github/workflows/reusable_auth_function_ci.yml

  api_tests:
    uses: ./.github/workflows/reuseable_api_unittests.yml
    secrets: inherit
