name: Continuous Integration Frontend

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"

  pull_request:
    branches:
      - "main"
    paths:
      - "frontend/**"

jobs:
  frontend_ci:
    uses: ./.github/workflows/reusable_frontend_ci.yml
