# leaving this in the repo for now as its a useful action that can be used
# to speed up debugging of frontend deployment.

# have disabled all triggers so it shouldn't run.

name: Push

on:
  push:
    #branches: [feat/84-configure-lambda]
    branches: [branch-name-that-doesnt-exist]

env:
  TF_VERSION: 1.0.5
  environment: dev
  organization: bcgov

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}


      # Steps to deploy the sample API
      # Steps to deploy Ian's python as a lambda
      - name: Install and Package Dependencies - Ians Code
        run: |
          cd server/backend
          mkdir packaging
          cd packaging
          pip install -t . -r ../requirements.txt
          zip -r9 ../../fam-ui-api.zip .
          cd ..
          rm -rf packaging
          cd ../../
          cd server/backend
          zip -u ../fam-ui-api.zip -r api/ -x database/**\* tests/**\* venv/**\* .env
          cd ..

      - name: Upload zip file artifact Kevin
        uses: actions/upload-artifact@v2
        with:
          name: fam-ui-api
          path: ./server/fam-ui-api.zip
          if-no-files-found: error


      - name: Auth function zip
        run: |
          mkdir auth_function_packaging
          rsync -r server/auth_function/* auth_function_packaging -F --exclude=requirements.txt --exclude=test
          pip install -t auth_function_packaging -r server/auth_function/requirements.txt
          cd auth_function_packaging
          zip -r9 ../server/fam_auth_function.zip .
          cd ..
          rm -rf auth_function_packaging

      - name: Auth function upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: fam-auth-function
          path: ./server/fam_auth_function.zip
          if-no-files-found: error


      - name: Deploying back-end using terraform
        run: |
          cd server

          # calculate the db_cluster_snapshot_identifier, attempting to ensure it
          # is less than 63 characters.
          db_cluster_snapshot_identifier="pre-flyway-${{ github.ref_name }}-${{ github.sha }}"
          if ((echo ${{ github.ref_name }} | wc -c ) > 12)
          then
              commit=${{ github.ref_name }}
              db_cluster_snapshot_identifier="pre-flyway-${{ github.ref_name }}-${commit:0:7}"
          fi
          # remove non alphanumeric characters
          db_cluster_snapshot_identifier=$(echo $db_cluster_snapshot_identifier |  tr -d '\n' | tr -cs '[-][:alnum:]' '-' )


          cat <<EOF > backend.hcl
          organization = "${{ env.organization }}"
          workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-backend" }
          EOF
          cat > github.auto.tfvars <<EOF
          github_repository = "https://github.com/${{ github.repository }}"
          github_branch = "${{ github.ref_name }}"
          github_commit = "${{ github.sha }}"
          github_event = "${{ github.event_name }}"
          oidc_idir_dev_idp_client_id = "${{ secrets.OIDC_IDIR_DEV_IDP_CLIENT_ID }}"
          oidc_idir_dev_idp_client_secret = "${{ secrets.OIDC_IDIR_DEV_IDP_CLIENT_SECRET }}"
          oidc_idir_dev_idp_issuer = "${{ secrets.OIDC_IDIR_DEV_IDP_ISSUER }}"
          oidc_bceid_business_dev_idp_client_id = "${{ secrets.OIDC_BCEID_BUSINESS_DEV_IDP_CLIENT_ID }}"
          oidc_bceid_business_dev_idp_client_secret = "${{ secrets.OIDC_BCEID_BUSINESS_DEV_IDP_CLIENT_SECRET }}"
          oidc_bceid_business_dev_idp_issuer = "${{ secrets.OIDC_BCEID_BUSINESS_DEV_IDP_ISSUER }}"
          db_cluster_snapshot_identifier = "$db_cluster_snapshot_identifier"
          EOF
          terraform init -backend-config=backend.hcl
          terraform apply -auto-approve
          #terraform plan
