name: Deploy to Test Environment

on:
  push:
    branches: [feat/67-pipeline-support]

jobs:

  build:
    name: Build and test components
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: |
          echo "Testing GitHub Actions Dependencies"   

  aws-test-deployment:
    uses: ./.github/workflows/reusable_terraform_server.yml
    with: 
      environment_name: test
      tfc_workspace: -test-backend
      tf_subcommand: destroy
    secrets: 
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}

