name: Deploy to Test Environment

on:
  push:
    branches: [feat/67-pipeline-support]

jobs:

  build:
    name: Build and test components
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: |
          echo "Testing GitHub Actions Dependencies"   

  aws-test-deployment:

    name: 1. Deploy to AWS TEST environment
    needs: [build]
    uses: ./.githhub/workflows/reusable_terraform_server.yml
    runs-on: ubuntu-latest
    environment: test
    with: 
      environment_name: test
      tfc-workspace: ${{ secrets.LICENCEPLATE }}-test         
      tf-subcommand: apply