name: Deprovision Test Environment

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.2.2
  TG_VERSION: 0.37.1
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: test  

  deprovision-test-environment:

    name: 1. Deprovision AWS TEST environment
    runs-on: ubuntu-latest
    environment: test
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Setup Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Destroy
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          LICENCEPLATE: ${{ secrets.LICENCEPLATE }}
        run: terragrunt run-all destroy --terragrunt-non-interactive