name: Terraform destroy

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.0.5
  environment: dev
  organization: bcgov

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: destroying the  back-end using terraform
        run: |
          cd server
          cat <<EOF > backend.hcl
          organization = "${{ env.organization }}"
          workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-backend" }
          EOF


          terraform init -backend-config=backend.hcl
          terraform destroy -auto-approve

      - name: destroying front-end and deploying Frontend using terraform
        run: |
          cd client
          cat <<EOF > backend.hcl
          organization = "${{ env.organization }}"
          workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-frontend" }
          EOF

          terraform init -backend-config=backend.hcl
          terraform destroy -auto-approve
