name: DEPLOY Development Environment (Frontend)

on:
  workflow_dispatch:

jobs:

  aws-test-deployment:
    uses: ./.github/workflows/reusable_terraform_frontend.yml
    with: 
      environment_name: dev
      tf_subcommand: apply
    secrets: 
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
