name: DESTROY Development Environment

on:
  workflow_dispatch:

jobs:

  aws-dev-destruction:
    uses: ./.github/workflows/reusable_terraform_server.yml
    with: 
      environment_name: dev
      tfc_workspace_suffix: dev-backend
      tf_subcommand: destroy
    secrets: 
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}

