name: DEPLOY Development Environment

on:
  workflow_dispatch:

jobs:

  aws-dev-deployment-server:
    uses: ./.github/workflows/reusable_terraform_server.yml
    with:
      environment_name: dev
      tf_subcommand: apply
      execute_flyway: true
    secrets:
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
      oidc_idir_idp_client_secret: "${{ secrets.OIDC_IDIR_IDP_CLIENT_SECRET }}"
      oidc_bceid_business_idp_client_secret: "${{ secrets.OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"

  aws-dev-deployment-frontend:
    needs: aws-dev-deployment-server
    uses: ./.github/workflows/reusable_terraform_frontend.yml
    with:
      environment_name: dev
      tf_subcommand: apply
    secrets:
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
