name: DESTROY Development Backend

on:
  workflow_dispatch:

jobs:

  aws-dev-destruction-server:
    uses: ./.github/workflows/reusable_terraform_server.yml
    with:
      environment_name: dev
      tf_subcommand: destroy
    secrets:
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
      dev_oidc_idir_idp_client_secret: "${{ secrets.DEV_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      test_oidc_idir_idp_client_secret: "${{ secrets.TEST_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      prod_oidc_idir_idp_client_secret: "${{ secrets.PROD_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      dev_oidc_bceid_business_idp_client_secret: "${{ secrets.DEV_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
      test_oidc_bceid_business_idp_client_secret: "${{ secrets.TEST_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
      prod_oidc_bceid_business_idp_client_secret: "${{ secrets.PROD_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
      forest_client_api_api_key: "${{ secrets.FOREST_CLIENT_API_API_KEY }}"
      dev_oidc_bcsc_idp_client_secret: "${{ secrets.DEV_OIDC_BCSC_IDP_CLIENT_SECRET }}"
      test_oidc_bcsc_idp_client_secret: "${{ secrets.TEST_OIDC_BCSC_IDP_CLIENT_SECRET }}"
      prod_oidc_bcsc_idp_client_secret: "${{ secrets.PROD_OIDC_BCSC_IDP_CLIENT_SECRET }}"
      idim_proxy_api_api_key: "${{ secrets.IDIM_PROXY_API_API_KEY }}"

  # Commenting out the destroy because we want cloudfront domain to be persistent
  # for DNS configuration reasons

  # aws-dev-destruction-frontend:
  #   needs: aws-dev-destruction-server
  #   uses: ./.github/workflows/reusable_terraform_frontend.yml
  #   with:
  #     environment_name: dev
  #     tf_subcommand: destroy
  #   secrets:
  #     licenceplate: ${{ secrets.LICENCEPLATE}}
  #     tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}