name: LZA DEPLOY Tools Environment

on:
  workflow_dispatch:
  push:
    branches:
      # Enable a specific branch to temporarily test in the tools environment.
      - "feat/laz-migration"

jobs:
  aws-tools-deployment-server:
    uses: ./.github/workflows/lza_reusable_terraform_server.yml
    with:
      environment_name: tools
      tf_subcommand: apply
      # execute_flyway: true

    secrets:
      licenceplate: ${{ secrets.LZA_LICENCEPLATE}}
