name: Terraform CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - "terraform-frontend/**"
      - "infrastructure/**"
      - ".github/workflows/reusable_terraform_server.yml"
      - ".github/workflows/pr_open_terraform_ci.yml"

jobs:
  terraform:
    environment: dev
    steps:
      - name: backend-terraform-plan
        uses: ./.github/workflows/reusable_terraform_server.yml
        with:
          environment_name: dev
          tf_subcommand: plan
          execute_flyway: false
        env:
          licenceplate: ${{ secrets.LICENCEPLATE}}
          tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
          dev_oidc_idir_idp_client_secret: "${{ secrets.DEV_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          test_oidc_bceid_business_idp_client_secret: "${{ secrets.TEST_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          prod_oidc_idir_idp_client_secret: "${{ secrets.PROD_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          dev_oidc_bceid_business_idp_client_secret: "${{ secrets.DEV_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
          test_oidc_idir_idp_client_secret: "${{ secrets.TEST_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
          prod_oidc_bceid_business_idp_client_secret: "${{ secrets.PROD_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"

      - name: frontend-terraform-plan
        uses: ./.github/workflows/reusable_terraform_frontend.yml
        with:
          environment_name: dev
          tf_subcommand: plan
        env:
          licenceplate: ${{ secrets.LICENCEPLATE}}
          tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: backend-terraform-plan-destroy
        uses: ./.github/workflows/reusable_terraform_server.yml
        with:
          environment_name: dev
          # This command can detect issues with the terraform destory: graph -verbose -draw-cycles -type=plan-destroy
          # Only need for the backend because we don't destroy the frontend.
          tf_subcommand: plan -destory
          execute_flyway: false
        env:
          licenceplate: ${{ secrets.LICENCEPLATE}}
          tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
          dev_oidc_idir_idp_client_secret: "${{ secrets.DEV_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          test_oidc_bceid_business_idp_client_secret: "${{ secrets.TEST_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          prod_oidc_idir_idp_client_secret: "${{ secrets.PROD_OIDC_IDIR_IDP_CLIENT_SECRET }}"
          dev_oidc_bceid_business_idp_client_secret: "${{ secrets.DEV_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
          test_oidc_idir_idp_client_secret: "${{ secrets.TEST_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
          prod_oidc_bceid_business_idp_client_secret: "${{ secrets.PROD_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
