name: DEPLOY Development Environment

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "main"
    paths:
      - "server/**"


jobs:

  aws-dev-deployment-server:
    uses: ./.github/workflows/reusable_terraform_server.yml
    with:
      environment_name: dev
      tf_subcommand: plan
      execute_flyway: false
    secrets:
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}
      dev_oidc_idir_idp_client_secret: "${{ secrets.DEV_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      test_oidc_bceid_business_idp_client_secret: "${{ secrets.TEST_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      prod_oidc_idir_idp_client_secret: "${{ secrets.PROD_OIDC_IDIR_IDP_CLIENT_SECRET }}"
      dev_oidc_bceid_business_idp_client_secret: "${{ secrets.DEV_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
      test_oidc_idir_idp_client_secret: "${{ secrets.TEST_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"
      prod_oidc_bceid_business_idp_client_secret: "${{ secrets.PROD_OIDC_BCEID_BUSINESS_IDP_CLIENT_SECRET }}"

