name: Run CI Auth Function

on:
  push:
    branches:
      - "ci/649-test-coverage"

env:
  POSTGRES_USER: fam_proxy_api
  POSTGRES_PASSWORD: test
  POSTGRES_HOST: localhost
  POSTGRES_DB: fam
  POSTGRES_PORT: 5432

jobs:
  auth-function-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run FAM API Tests
        working-directory: server/backend
        env:
          FC_API_TOKEN: ${{ secrets.FOREST_CLIENT_API_API_KEY }}
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pytest --cov=api --cov-report=xml -v --md=report.md --emoji

      - name: Publish FAM API Tests
        working-directory: server/backend
        if: always()
        run: |
          sed -i 's/# Test Report/# FAM API Tests/' report.md
          sed -i '2i <details><summary>Click to expand!</summary>' report.md
          sed -i '$a</details>' report.md
          cat report.md >> $GITHUB_STEP_SUMMARY


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: always()
        with:
          projectBaseDir: server/backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH }}

