name: api unit tests

# on:
#   workflow_call:

# debugging
on:
  push:
    branches: [feat/94-integrate-unit-tests]

env:
  environment: dev
  organization: bcgov
  POSTGRES_DB: fam
  POSTGRES_USER: fam_test
  POSTGRES_PASSWORD: test
  USE_POSTGRES: false

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      # doing this to ensure using same python version as the lambda will be
      # using
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python --version
          cd server/backend
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd server/backend
          pytest
