name: Run CI Auth Function

on:
  push:
    branches:
      - "ci/649-test-coverage"

env:
  POSTGRES_USER: fam_proxy_api
  POSTGRES_PASSWORD: test
  POSTGRES_HOST: localhost
  POSTGRES_DB: fam
  POSTGRES_PORT: 5432

jobs:
  auth-function-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Auth function install python test dependencies
        working-directory: server/auth_function
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Auth function run pytest on postgres
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          # 'pytest-action' still works from root directory so pass in 'server/auth_function'
          custom-arguments: 'server/auth_function --cov=. --cov-report=xml'

      - name: debug
        run: |
          ls
          ls ../
          ls ../../


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: server/auth_function
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH }}

