name: CI for Frontend

on:
  workflow_call:    

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Test Frontend
        working-directory: frontend
        run: |
          npm run test-coverage

      # TODO: upload coverage results to SonarCloud
      
