name: Run CI Auth Function

on:
  workflow_call:

env:
  POSTGRES_USER: fam_proxy_api
  POSTGRES_PASSWORD: test
  POSTGRES_HOST: localhost
  POSTGRES_DB: fam
  POSTGRES_PORT: 5432

jobs:
  auth-function-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run Auth Function Tests
        working-directory: server/auth_function
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pytest --cov=. --cov-report=xml -v --md=report.md --emoji
          sed -i 's/# Test Report/# FAM Auth Function Tests/' report.md
          sed -i '2i <details><summary>Click to expand!</summary>' report.md
          sed -i '$a</details>' report.md
          cat report.md >> $GITHUB_STEP_SUMMARY

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: server/auth_function
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH }}

      - name: Auth function zip
        run: |
          mkdir auth_function_packaging
          rsync -r server/auth_function/* auth_function_packaging -F --exclude=requirements.txt --exclude=test --exclude=requirements-dev.txt
          pip install -t auth_function_packaging -r server/auth_function/requirements.txt -r server/auth_function/requirements-dev.txt
          cd auth_function_packaging
          zip -r9 ../infrastructure/server/fam_auth_function.zip .
          cd ..
          rm -rf auth_function_packaging

      - name: Auth function upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: fam-auth-function-zip
          path: ./infrastructure/server/fam_auth_function.zip
          if-no-files-found: error
