name: api unit tests

on:
  workflow_call:
    inputs:
    # leaving here as an example of an input
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

env:
  environment: dev
  organization: bcgov

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest

    #Run local postgres for testing
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: fam
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      # doing this to ensure using same python version as the lambda will be
      # using
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd server/backend
          pip install -r requirements.txt
