name: DEPLOY Test Environment (Frontend Only)

# on:
#   workflow_dispatch:

on: 
  push:
    branches:
      - "fix/270-update-frontend-s3"

jobs:

  aws-test-deployment-frontend:
    uses: ./.github/workflows/reusable_terraform_frontend.yml
    with: 
      environment_name: test
      tf_subcommand: apply
    secrets: 
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}      

  bump-version-tag:
    needs: aws-test-deployment-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main, fix/270-update-frontend-s3

