name: DEPLOY Test Environment (Frontend Only)

on:
  workflow_dispatch:

jobs:

  aws-test-deployment-frontend:
    uses: ./.github/workflows/reusable_terraform_frontend.yml
    with: 
      environment_name: test
      tf_subcommand: apply
    secrets: 
      licenceplate: ${{ secrets.LICENCEPLATE}}
      tfc_team_token: ${{ secrets.TFC_TEAM_TOKEN }}      

