name: Pull Request

on:
  pull_request:
    branches: [dev]
env:
  environment: dev
  organization: bcgov

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Fixing terraform state
        run: |
          cd server
          cat <<EOF > backend.hcl
          organization = "${{ env.organization }}"
          workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-backend" }
          EOF
          terraform init -backend-config=backend.hcl
          terraform state list
          # terraform state rm module.rds_proxy.aws_cloudwatch_log_group.this[0]
          # terraform state list
